server:
  port: 8082

spring:
  application:
    name: buddy-memory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/buddydb
    username: buddy
    password: buddy123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    com.buddy: DEBUG
