version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: buddy
      POSTGRES_PASSWORD: buddy123
      POSTGRES_DB: buddydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./memory-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buddy -d buddydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
